# Generated by Django 3.1.3 on 2022-06-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_count', models.IntegerField(blank=True, null=True)),
                ('od_box_count', models.IntegerField(blank=True, null=True)),
                ('d_day', models.DateTimeField(blank=True)),
                ('od_date', models.DateTimeField(blank=True)),
                ('del_check', models.CharField(blank=True, max_length=200)),
                ('order_note', models.TextField(blank=True)),
                ('out_note', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('total_sum', models.IntegerField(blank=True, null=True)),
                ('img1', models.ImageField(blank=True, upload_to='')),
                ('img2', models.ImageField(blank=True, upload_to='')),
                ('img3', models.ImageField(blank=True, upload_to='')),
                ('aaa', models.CharField(blank=True, max_length=200)),
                ('bbb', models.CharField(blank=True, max_length=200)),
                ('ccc', models.CharField(blank=True, max_length=200)),
                ('ddd', models.CharField(blank=True, max_length=200)),
                ('eee', models.CharField(blank=True, max_length=200)),
                ('fff', models.IntegerField(blank=True, null=True)),
                ('ggg', models.IntegerField(blank=True, null=True)),
                ('hhh', models.IntegerField(blank=True, null=True)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(blank=True, null=True)),
                ('org_bar', models.IntegerField(blank=True, null=True)),
                ('sale_bar', models.IntegerField(blank=True, null=True)),
                ('p_name', models.CharField(blank=True, max_length=200)),
                ('iq', models.IntegerField(blank=True, null=True)),
                ('p_price', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odp_name', models.CharField(blank=True, max_length=200)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('phon_num', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
