# Generated by Django 3.1.3 on 2022-07-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
        migrations.AlterField(
            model_name='products',
            name='iq',
            field=models.IntegerField(blank=True, null=True, verbose_name='입수'),
        ),
        migrations.AlterField(
            model_name='products',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='위치정보'),
        ),
        migrations.AlterField(
            model_name='products',
            name='org_bar',
            field=models.IntegerField(blank=True, null=True, verbose_name='원코드'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='상품코드'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='출고가'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sale_bar',
            field=models.IntegerField(blank=True, null=True, verbose_name='판매코드'),
        ),
        migrations.AlterModelTable(
            name='products',
            table='midas_product',
        ),
    ]
