# Generated by Django 3.1.3 on 2022-07-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0002_auto_20220706_1557'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
