# Generated by Django 3.1.3 on 2022-07-07 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0003_auto_20220707_1314'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='midas_Products',
        ),
    ]
