# Generated by Django 3.1.3 on 2022-07-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0004_auto_20220707_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
    ]
