# Generated by Django 3.2.14 on 2022-07-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0006_alter_order_list_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='order_list',
            name='buyer_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_list',
            name='odp_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order_list',
            name='phon_num',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='d_day',
            field=models.DateTimeField(),
        ),
    ]
