# Generated by Django 3.2.14 on 2022-07-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0007_auto_20220715_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
