# Generated by Django 3.2.14 on 2022-07-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0009_alter_order_list_d_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='buyer_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_list',
            name='od_date',
            field=models.DateTimeField(),
        ),
    ]
