# Generated by Django 3.2.14 on 2022-07-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0011_alter_order_list_od_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='od_date',
            field=models.DateTimeField(),
        ),
    ]
