# Generated by Django 3.2.14 on 2022-07-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0013_auto_20220718_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='d_day',
            field=models.DateTimeField(blank=True),
        ),
    ]
