# Generated by Django 3.2.14 on 2022-07-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0014_alter_order_list_d_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
