# Generated by Django 3.2.14 on 2022-07-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0015_alter_order_list_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='od_list',
            field=models.JSONField(default='{}'),
        ),
    ]
