# Generated by Django 3.2.14 on 2022-07-25 08:02

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0016_order_list_od_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='od_list',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
    ]
