# Generated by Django 3.2.14 on 2022-07-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0018_alter_order_list_od_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='s_iq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_list',
            name='s_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order_list',
            name='s_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_list',
            name='s_product',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
