# Generated by Django 3.2.14 on 2022-07-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0019_auto_20220727_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='s_org_bar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
