# Generated by Django 3.1.3 on 2026-01-14 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20251215_0932'),
        ('cart', '0002_auto_20220817_1122'),
    ]

    operations = [
    ]
