# Generated by Django 3.1.3 on 2021-09-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pay_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('base_pay', models.IntegerField()),
                ('overtime_pay', models.IntegerField()),
                ('holiday_pay', models.IntegerField()),
                ('meal_cost', models.IntegerField()),
                ('car_fee', models.IntegerField()),
                ('incentive1', models.IntegerField()),
                ('incentive2', models.IntegerField()),
                ('total_pay', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('local_tax', models.IntegerField()),
                ('health', models.IntegerField()),
                ('longterm_care', models.IntegerField()),
                ('National_Pension', models.IntegerField()),
                ('Employment', models.IntegerField()),
                ('deduction_sum', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('etc_explain', models.TextField()),
                ('accesstoken', models.CharField(max_length=200, default="charField")),
                ('yymm', models.CharField(max_length=200, default="charField")),
            ],
        ),
    ]
