# Generated by Django 3.1.3 on 2022-07-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_list',
            name='Employment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pay_list',
            name='National_Pension',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pay_list',
            name='car_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pay_list',
            name='health',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pay_list',
            name='holiday_pay',
            field=models.CharField(default='charField', max_length=200),
        ),
        migrations.AlterField(
            model_name='pay_list',
            name='incentive1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pay_list',
            name='incentive2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pay_list',
            name='local_tax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pay_list',
            name='longterm_care',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pay_list',
            name='meal_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pay_list',
            name='overtime_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pay_list',
            name='tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
