# Generated by Django 3.1.3 on 2022-07-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paystub', '0002_auto_20220706_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pay_list',
        ),
    ]
