# Generated by Django 3.1.3 on 2022-04-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='aaa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='bbb',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='ccc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='create_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='ddd',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='eee',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='select_form',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
