# Generated by Django 3.1.3 on 2026-04-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eas', '0002_auto_20220421_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='manager_name',
            field=models.CharField(blank=True, default='혁만', max_length=20),
        ),
    ]
