# Generated by Django 3.1.3 on 2026-04-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eas', '0003_request_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='note_image',
            field=models.ImageField(blank=True, null=True, upload_to='eas/note/'),
        ),
    ]
