# Generated by Django 3.1.3 on 2025-12-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='소속')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='성명')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('manager_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='담당 서명')),
                ('admin_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='총무 서명')),
                ('submit_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
