# Generated by Django 3.1.3 on 2025-12-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='approved_device',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='approved_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
